// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpwcidrrqgnznzefpnco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwd2NpZHJycWduem56ZWZwbmNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NjgwNDUsImV4cCI6MjA2MDA0NDA0NX0.B0_bLyu8TpW-AToeE7j9YE-9a4p9OPUQUVUhimS0B74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);